name: PR Automation

on:
  pull_request:
    types: [opened]

jobs:
  pr-automation:
    name: PR Automation
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Add labels based on files changed
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
